### PR TITLE
Make the Duo use the RNDIS host as a default gw.

### PR DESCRIPTION
**Pull request by mcdonc**
Use dnsmasq hacks to detect the IP address of the RNDIS host and set it as the default gateway.

Also document what should be done on the host to get ip forwarding and masquerading working.

### CODE REVIEW

**Comment by NickCao** [comment]
I feel that we might should do the opposite, run the dhcp server on the host and client on the duo, that makes gateway configuration work by default.

**Comment by mcdonc** [comment]
> I feel that we might should do the opposite, run the dhcp server on the host and client on the duo, that makes gateway configuration work by default.

Yeah, that would make more sense to me too, but that's not how RNDIS works.  We could ditch RNDIS, but I'm not sure how to replace it with anything more sensible.

**Comment by NickCao** [comment]
> but that's not how RNDIS works

Isn't RDNIS just like an ethernet cable (but over USB)? It should work both ways.

**Comment by mcdonc** [comment]
> > but that's not how RNDIS works
> 
> Isn't RDNIS just like an ethernet cable (but over USB)? It should work both ways.

Oh yeah, I guess that's true!  Sorry, I wasn't thinking clearly.

It would be great if we could even get rid of DHCP entirely.

**Comment by mcdonc** [comment]
Much saner now.

**Comment by NickCao** [comment]
We may also drop the static mac address thing.

**Comment by mcdonc** [comment]
Just noticed that without the static host MAC address, following the instructions I give in duo-256.nix to set up a static host IP will tie the connection to the interface represented by the Duo's specific initial random MAC, and rebooting the host or replugging the device may cause a second connection to be created, which will have to be configured with the right stuff, etc etc.  You can fix this by removing the MAC from the "Restrict to device" list, which, at least in the KDE UI, causes it to be only associated with the interface, not a specific MAC on that interface.

**Pull request merged**
